/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.willpall.mobrepellent;

import org.bukkit.Bukkit;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;

import java.io.File;
import java.util.ArrayList;
import java.util.logging.Logger;

public class MobRepellent extends JavaPlugin implements Listener {
	private Logger log = Logger.getLogger( "Minecraft" );
	private MobRepellentList repellers;
	private ArrayList<World> worlds;
	private MobRepellentConfiguration config;
	private int delayLoadTask;

    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(this, this);

        // Config is needed before anything else
		config = new MobRepellentConfiguration( this );

		File pluginDir = new File( "plugins/MobRepellent/" );
		if( !pluginDir.exists() )
		{
			pluginDir.mkdir();
			this.log.info( "[MobRepellent] Folder not found, creating new one." );
		}

		delayLoadTask = getServer().getScheduler().scheduleSyncDelayedTask( this, new MobRepellentDelayLoadRunnable( this ) );

        getCommand("mrlist").setExecutor(this);
        getCommand("mrreload").setExecutor(this);
        getCommand("mrremove").setExecutor(this);
        getCommand("mrremoveall").setExecutor(this);

		getServer().getLogger().info( "MobRepellent (v" + VERSION + ") is enabled!" );
    }

    @Override
	public void onDisable()
	{
		config.save();
	}

    @Override
    public boolean onCommand( CommandSender sender, Command command, String label, String[] args )
	{
		// This is for whether we want console-only or player command
		Player player = null;
		
		if( sender instanceof Player )
			player = (Player) sender;
		
		if( command.getName().equalsIgnoreCase( "mrlist" ) )
		{
			// decline if player doesn't have permission
			if( ( player != null ) &&
				!player.hasPermission( "mobrepellent.list" ) )
			{
				player.sendMessage(Component.text("You do not have permission to use that command.", NamedTextColor.RED));
				return true;
			}
			
			ArrayList<MobRepeller> list = repellers.getList();
			
			if( list.isEmpty() )
			{
				if( player != null )
				{
					player.sendMessage(Component.text("No repellers loaded.", NamedTextColor.GREEN));
				}
				else
					log.info( "[MobRepellent] No repellers loaded." );
			}
			else
			{
				if( player != null )
					player.sendMessage(Component.text("Loaded Repellers:", NamedTextColor.DARK_GREEN));
				else
					log.info( "[MobRepellent] Loaded Repellers:" );
				
				for( int i = 0; i < list.size(); i++ )
				{
					MobRepeller repeller = list.get( i );

					if( player != null )
					{
						player.sendMessage(Component.text(Integer.toString(i + 1) + " - W: "
								+ list.get(i).getWorld().getName() + " - Co-ord: " + repeller.getX() + ", " + repeller.getY()
								+ ", " + repeller.getZ(), NamedTextColor.GREEN));
					}
					else
						log.info( "    " + ( i + 1 ) + " - W: " + list.get( i ).getWorld().getName() + " - Co-ord: "
								+ repeller.getX() + ", " + repeller.getY() + ", " + repeller.getZ() );
				}
			}
			return true;
		}
		else if( command.getName().equalsIgnoreCase( "mrreload" ) )
		{
			// decline if player doesn't have permission
			if( ( player != null ) &&
				!player.hasPermission( "mobrepellent.list" ) )
			{
				player.sendMessage(Component.text("You do not have permission to use that command.", NamedTextColor.RED));
				return true;
			}
			
			this.config.reload();
			if( player != null )
			{
				player.sendMessage(Component.text("MobRepellent config successfully reloaded.", NamedTextColor.GREEN));
			}
			else
				log.info( "[MobRepellent] Config successfully reloaded." );
		
			return true;
		}
		else if( command.getName().equalsIgnoreCase( "mrremove" ) )
		{
			// decline if player doesn't have permission
			if( ( player != null ) &&
				!player.hasPermission( "mobrepellent.remove" ) )
			{
				player.sendMessage(Component.text("You do not have permission to use that command.", NamedTextColor.RED));
				return true;
			}
			
			int repellerNum = -1;
			try
			{
				repellerNum = Integer.parseInt( args[0] );

				if( repellers.remove( repellerNum ) )
				{
					if( player != null )
						player.sendMessage(Component.text("Removed repeller #" + repellerNum, NamedTextColor.GREEN));
					else
						log.info( "[MobRepellent] Removed repeller #" + repellerNum );
					
					return true;
				}
			}
			catch( Exception e )
			{
				// Do nothing
			}
			return false;
		}
		else if( command.getName().equalsIgnoreCase( "mrremoveall" ) )
		{
			// decline if player doesn't have permission
			if( ( player != null ) &&
				!player.hasPermission( "mobrepellent.removeall" ) )
			{
				player.sendMessage(Component.text("You do not have permission to use that command.", NamedTextColor.RED));
				return true;
			}
			
			repellers.removeAll();
			if( player != null )
				player.sendMessage(Component.text("Removed all repellers.", NamedTextColor.GREEN));
			else
				log.info( "[MobRepellent] Removed all repellers" );
			
			return true;
		}
		
		return false;
	}
	
	public void reloadRepellers()
	{
		worlds = (ArrayList<World>) getServer().getWorlds();
		repellers = new MobRepellentList( "plugins/MobRepellent/", this );
	}
	
	public void loadPlugin()
	{
		getServer().getScheduler().cancelTask( delayLoadTask );
		// reload worlds, just in case
		worlds = (ArrayList<World>) getServer().getWorlds();
		repellers = new MobRepellentList( "plugins/MobRepellent/", this );
		
		MobRepellentEntityListener entityListener = new MobRepellentEntityListener( this );
		MobRepellentBlockListener blockListener = new MobRepellentBlockListener( this );
	
		getServer().getPluginManager().registerEvents( entityListener, this );
		getServer().getPluginManager().registerEvents( blockListener, this );
		getServer().getPluginManager().registerEvents( blockListener, this );
	}
	
	public MobRepellentConfiguration getMobRepellentConfiguration()
	{
		return this.config;
	}

/*
// Commented out as Minecraft/Bukkit 1.4.4 didn't like the override of this function
	public Logger getLogger()
	{
		return this.log;
	}
*/

	public MobRepellentList getRepellerList()
	{
		return this.repellers;
	}
	
	public ArrayList<World> getWorlds()
	{
		return worlds;
	}
	
	public void debug( String message )
	{
		if( config.getDebugMode() )
			log.info( message );
	}
	
	public static boolean isBaseOfRepeller( Block block, MobRepellentConfiguration configuration )
	{
		World w = block.getWorld();
		int x = block.getX();
		int y = block.getY();
		int z = block.getZ();
		
		if( ( configuration.getRadius( w.getBlockAt( x, y + 1, z ) ) != -1 ) &&
			( configuration.getRadius( w.getBlockAt( x, y + 2, z ) ) != -1 ) &&
			( configuration.getRadius( w.getBlockAt( x + 1, y, z ) ) != -1 ) &&
			( configuration.getRadius( w.getBlockAt( x - 1, y, z ) ) != -1 ) &&
			( configuration.getRadius( w.getBlockAt( x, y, z + 1 ) ) != -1 ) &&
			( configuration.getRadius( w.getBlockAt( x, y, z - 1 ) ) != -1 ) )
			return true;
		
		return false;
	}
}
