/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.willpall.mobrepellent;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MobRepellentTest {
    @Test void appHasAGreeting() {
        // MobRepellent classUnderTest = new MobRepellent();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        assertTrue(true);
    }
}
