# MobRepellent Configuration

# The 'Radius' values allow you to set the radius from the base of the 
# repeller that mobs will be repelled.
#
# The "Radius.ignore_below" variable allows one to restrict repelling to mobs
# that spawn from the base of the repeller and above. For instance, a repeller
# placed at "y=50" will never affect mobs spawning from "y=49" and below if
# "ignore_below" is set to "true".
#
# Ex: 'large: 50' will repel mobs a radius of 50 blocks from the base of
#     the large repeller. In other words, it will repel in a 100 block cube 
#     around the repeller.
Radius:
  small: 20
  medium: 30
  large: 50
  ignore_below: false

# The 'Blocks' values set the block data value to use for the repeller
# material. Certain blocks are not allowed because of gameplay/performance
# issues. If one of the forbidden blocks is defined, the plugin will default
# to diamond blocks.
#
# List of forbidden materials:
#   AIR
#   STONE
#   GRASS_BLOCK
#   DIRT
#   BEDROCK
#   WATER
#   LAVA
#   SAND
#   GRAVEL
#   SANDSTONE
#   SNOW_BLOCK
#   ICE
#   CLAY
#   NETHERRACK
#   SOUL_SAND
#   MYCELIUM
#   END_STONE
Blocks:
  small: IRON_BLOCK
  medium: GOLD_BLOCK
  large: DIAMOND_BLOCK

# The 'Mobs' values control configuration for mobs.
#
# "repel_neutral" sets whether to repel neutral mobs as well as hostile mobs.
# Values allowed are 'true' or 'false'
#
# "list" is a string list of mobs to repel. If left empty, it will repel all
# hostile mobs and repel all neutral mobs if "repel_neutral" is true.
#
# For example, to only repel creepers and skeletons use it like this:
# Mobs:
#   list:
#   - Creeper
#   - Skeleton
Mobs:
  repel_neutral: false
  list: 