# MobRepellent Configuration

# The 'radius' value allows you to set the radius from the base of the repeller
# that mobs will be repelled.
#
# Ex: 'radius: 50' will repel mobs a radius of 50 blocks from the base.
#     In other words, it will repel in a 100 block cube around the repeller.
radius: 50

# The 'block_id' value sets the block data value to use for the repeller
# material. Certain blocks are not allowed because of gameplay/performance
# issues. If one of the forbidden blocks is defined, the plugin will default
# to diamond blocks.
#
# List of forbidden IDs: 0, 1, 2, 3, 7, 8, 9, 10, 11, 12, 13, 24, 78,
#                        79, 82, 87, 88, 89
#
# For instance, '1' corresponds to stone block. Placing a single stone
# block adjacent to a large mountain of stone will cause every stone block
# in the mountain and every stone block adjacent to the mountain to be
# confused for a repeller. This causes massive performance issues and could
# cause mobs to become very very scarce.
block_id: 57