# MobRepellent Configuration

# The 'Radius' values allow you to set the radius from the base of the 
# repeller that mobs will be repelled.
#
# The "Radius.ignore_below" variable allows one to restrict repelling to mobs
# that spawn from the base of the repeller and above. For instance, a repeller
# placed at "y=50" will never affect mobs spawning from "y=49" and below if
# "ignore_below" is set to "true".
#
# Ex: 'large: 50' will repel mobs a radius of 50 blocks from the base of
#     the large repeller. In other words, it will repel in a 100 block cube 
#     around the repeller.
Radius:
  small: 20
  medium: 30
  large: 50
  ignore_below: false

# The 'BlockID' values set the block data value to use for the repeller
# material. Certain blocks are not allowed because of gameplay/performance
# issues. If one of the forbidden blocks is defined, the plugin will default
# to diamond blocks.
#
# List of forbidden IDs: 0, 1, 2, 3, 7, 8, 9, 10, 11, 12, 13, 24, 78,
#                        79, 82, 87, 88, 110, 121
#
# For instance, '1' corresponds to stone block. Placing a single stone
# block adjacent to a large mountain of stone will cause every stone block
# in the mountain and every stone block adjacent to the mountain to be
# confused for a repeller. This causes massive performance issues and could
# cause mobs to become very very scarce.
#
# You can also set specific block types by using an '@' symbol. For
# instance, to restrict small repellers to only orange wool you would use:
# 
# small: 35@1
#
# Setting small to 35@0 will only allow repellers out of white wool.
# Using "small: 35" will allow all types of wool.
BlockID:
  small: 42
  medium: 41
  large: 57

# The 'Mobs' values control configuration for mobs.
#
# "repel_neutral" sets whether to repel neutral mobs as well as hostile mobs.
# Values allowed are 'true' or 'false'
#
# "list" is a string list of mobs to repel. If left empty, it will repel all
# hostile mobs and repel all neutral mobs if "repel_neutral" is true.
#
# For example, to only repel creepers and skeletons use it like this:
# Mobs:
#   list:
#   - Creeper
#   - Skeleton
Mobs:
  repel_neutral: false
  list: 