# MobRepellent Configuration
# 
# For more info, see the full sample config.yml at:
#     https://github.com/WillPall/MobRepellent/raw/master/docs/config.yml
# 
# Config options:
#     Radius: set the cuboid block radius of the small/medium/large repellers
#     BlockID: set the data values for the blocks each repeller type uses
#     Mobs.repel_neutral: toggle repelling of neutral mobs
#     Mobs.list: list of mob types to repel (see the sample config.yml at
#                the link given above). If left empty, will repel all hostile
#                mobs and all neutral if "repel_neutral" is true.
Radius:
  small: 20
  medium: 30
  large: 50
BlockID:
  small: 42
  medium: 41
  large: 57
Mobs:
  repel_neutral: false
  list:

#small_radius: 20
#medium_radius: 30
#large_radius: 50
#small_id: 42
#medium_id: 41
#large_id: 57
#repel_neutral_mobs: false
#mobs_to_repel: 